spring:
    #datasource:
    #    url: ${db.url:}
    #    username: ${db.username}
    #    password: ${db.password}
    mustache:
      prefix:
        classpath:/templates/
      suffix:
        .mustache
      servlet:
        expose-request-attributes: true