apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "traefik-movies-api-ingress"
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`movie.skycomposer.net`) && PathPrefix(`/movies-api`)
    kind: Rule
    services:
    - name: movies-api
      port: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "traefik-movies-ui-ingress"
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`movie.skycomposer.net`) && PathPrefix(`/movies-ui`)
    kind: Rule
    services:
    - name: movies-ui
      port: 80       

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "traefik-keycloak-ingress"
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`movie.skycomposer.net`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: keycloak
      port: 80