const val dockerComposePluginVersion="0.14.12"
const val testContainersVersion = "1.16.2"
const val restAssuredVersion = "4.3.3"
const val springFoxVersion = "2.9.2"
const val springBootVersion = "2.6.2"
