version: '3'
services:

  mysql:
    image: mysql:8.0.27
    #image: mysql:5.7.28
    platform: linux/amd64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
      - MYSQL_DATABASE=service_template

  prometheus:
    build: ./prometheus
    ports:
      - 9090:9090

  keycloak:
    build: ./keycloak
    ports:
      - 8091:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/realm.json
      - DB_VENDOR=h2

  zipkin:
    image: openzipkin/zipkin:2.21
    ports:
      - "9411:9411"
    environment:
      JAVA_OPTS: -Xmx64m

  keycloak-test-proxy:
    build: ./keycloak-test-proxy
    ports:
      - 8093:80
    depends_on:
      - keycloak

  service-template:
      build: ./service-template-main
      image: ghcr.io/skyglass/service-template
      ports:
        - 8080:8080
      depends_on:
        - keycloak
        - mysql
        - zipkin
      environment:
        - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/auth/realms/service-template/protocol/openid-connect/certs
        - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/auth/realms/service-template
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/service_template
        - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411/

# Disables connecting to mysql - https://hub.docker.com/r/jboss/keycloak/
