version: '3'
services:

  mysql:
    image: mysql:8.0.27
    platform: linux/amd64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
      - MYSQL_DATABASE=service_template

  prometheus:
    build: ./prometheus
    ports:
      - 9090:9090

  zipkin:
    image: openzipkin/zipkin:2.21
    ports:
      - "9411:9411"
    environment:
      JAVA_OPTS: -Xmx64m

