name: Build

on:
  push:
  pull_request:
    types:
      - opened
      - edited
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64

    - name: Build
      run: |
        # grr... testcontainers.reuse.enable=true needs to be in home dir
        cp service-template-test-containers/src/main/resources/dot.testcontainers.properties ~/.testcontainers.properties
        ./gradlew compileAll
        export DOCKER_HOST_IP=$(hostname -I | sed -e 's/ .*//g')
        echo DOCKER_HOST_IP=$DOCKER_HOST_IP
        ./gradlew validateEnvironment
        .github/workflows/verify-todos.py

    - name: Save test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: |
          ./build/reports
          **/build/reports/tests/
          **/build/test-results

    - name: get container logs
      run: ./.github/workflows/print-container-logs.sh
      if: ${{ always() }}

    - name: Save container logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: container-logs
        path: ~/container-logs
